name: Terraform Auto-Scaling

on:
  push:
    branches:
      - main
    paths:
      - 'Devops/Terraform/**'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd Devops/Terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd Devops/Terraform
          terraform plan -var-file="AutoscaleVar.Tfvars"

      - name: Terraform Apply
        run: |
          cd Devops/Terraform
          terraform apply -auto-approve -var-file="AutoscaleVar.Tfvars"
